#!/usr/bin/env bash
set -euo pipefail

# ---- 1) Require config via env vars ----
required_vars=(
  EMAIL TOKEN HOSTNAME DOMAIN TIMEZONE
  SMTP_HOST SMTP_PORT
  LANDSCAPE_VERSION
)

for v in "${required_vars[@]}"; do
  if [ -z "${!v:-}" ]; then
    echo "ERROR: Missing required env var: $v" >&2
    exit 1
  fi
done

# ---- 3) Start PostgreSQL ----
echo "Starting PostgreSQL..."
service postgresql start

# Wait for Postgres
if command -v pg_isready >/dev/null 2>&1; then
  for i in {1..30}; do
    if pg_isready -q; then
      echo "PostgreSQL is ready."
      break
    fi
    if [ "$i" -eq 30 ]; then
      echo "ERROR: PostgreSQL did not become ready in time." >&2
      exit 1
    fi
    sleep 1
  done
fi

# ---- 4) Start RabbitMQ ----
echo "Starting RabbitMQ..."
rabbitmq-server -detached

# Wait for RabbitMQ node & app to be fully up
for i in {1..30}; do
  # check_running = node + app up
  if rabbitmq-diagnostics -q check_running >/dev/null 2>&1; then
    echo "RabbitMQ is running."
    break
  fi

  # As a fallback, try to start the app if node is up but app isn't
  if rabbitmq-diagnostics -q ping >/dev/null 2>&1; then
    echo "RabbitMQ node is up but app not running yet, trying to start_app..."
    rabbitmqctl start_app >/dev/null 2>&1 || true
  fi

  if [ "$i" -eq 30 ]; then
    echo "ERROR: RabbitMQ did not become fully ready in time." >&2
    rabbitmq-diagnostics check_running || true
    exit 1
  fi

  sleep 1
done

# ---- 5) Run landscape-quickstart once ----
FQDN="${HOSTNAME}.${DOMAIN}"

if [ ! -f /var/lib/landscape/.quickstart_done ]; then
  echo "Running landscape-quickstart..."
  if ! landscape-quickstart; then
    echo "ERROR: landscape-quickstart failed" >&2
    # optionally dump logs here
    exit 1
  fi

  if [ -n "${FQDN}" ]; then
    echo "Configuring Landscape to use FQDN: ${FQDN}"

    # 1) Fix Landscape service.conf host
    if [ -f /etc/landscape/service.conf ]; then
      # replace entire 'host = ...' line
      sed -i "s/^host *= *.*/host = ${FQDN}/" /etc/landscape/service.conf
    fi

    # 2) Fix Apache vhosts generated by quickstart
    for f in /etc/apache2/sites-available/*.conf /etc/apache2/sites-enabled/*.conf; do
      [ -f "$f" ] || continue

      # ServerName localhost -> FQDN
      sed -i "s|^\s*ServerName\s\+localhost\s*$|    ServerName ${FQDN}|g" "$f"
      sed -i "s|^\s*ServerName\s\+127\.0\.0\.1\s*$|    ServerName ${FQDN}|g" "$f"

      # Optional: ensure we also accept the FQDN as alias if needed
      # (only if there's an alias for localhost)
      sed -i "s|^\s*ServerAlias\s\+localhost\s*$|    ServerAlias ${FQDN}|g" "$f"

      # Update explicit URLs pointing at localhost
      sed -i "s|https://localhost|https://${FQDN}|g" "$f"
      sed -i "s|http://localhost|http://${FQDN}|g" "$f"
    done
  fi

  touch /var/lib/landscape/.quickstart_done
else
  echo "Skipping landscape-quickstart (already done)."
fi

echo "Starting Apache in foreground..."
exec apachectl -D FOREGROUND &

echo "Starting Landscape services..."
if ! lsctl start; then
  echo "WARNING: 'lsctl start' returned non-zero exit code. Some services may have failed to start."
  # Show detailed status for debugging, but don't break the container
  lsctl status || true
fi

tail -f /var/log/apache2/error.log
